### ISSUE TITLE
很好的功能、可文件夹层数超过4层就不工作了

### ISSUE THREAD

**Issue by SY199505** [jianfenkezhan/i18njs#1]
非常感谢你的插件、解脱了繁杂的工作、看到能解决一下这个问题吗

**Comment by SY199505** [comment]
定位了问题 不是上面的原因、检测到下面的内容回卡死
`
                            {
                                required: true,
                                message: '新密码不能为空',
                            },
                            {
                                validator: this.validateToNextPassword,
                            },
                            {
                                min: 3,
                                message: '最小长度为3'
                            }`.replace(/("([^\\\"]*(\\.)?)*")|('([^\\\']*(\\.)?)*')|(\/{2,}.*?(\r|\n))|(\/\*(\n|.)*?\*\/)|((=)?(\s+)?(|`|"|')?(\s+)?[\u4e00-\u9faf]+('|"|`)?)/g, (word) => {
    console.log(word)
})

**Comment by jianfenkezhan** [comment]
可以提供一个小的demo吗？我跑一下看看

**Comment by SY199505** [comment]
> 可以提供一个小的demo吗？我跑一下看看

这个挺好找的 有大量空格回车的 就处理不来
后来我把空格回车换成特定字符就好了、处理完在换回来
找个vue或react项目就成
